### ISSUE TITLE
[BUG] New Bug

### ISSUE THREAD

**Issue by JarbasAl** [thecfu/scraparr#36]
**Describe the bug**

```
(ovos) miro@miro-ser9:~/compose $ docker logs scraparr 
/usr/local/bin/python: No module named scraparr.scraparr
```

**To Reproduce**

used docker compose from this repo

**Expected behavior**

unclear, was just checking it out the first time

**Additional context**
🤷

**Comment by TheGameProfi** [comment]
Hey,
could you please share your compose file and the version your using?
I just tested it on a fresh machine and there it worked

**Comment by p2bauer** [comment]
For myself, I'm running on kubernetes - pretty straightforward yaml though, here's the relevant snippet:
```      containers:
        - name: scraparr
          image: ghcr.io/thecfu/scraparr:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 5007
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /scraparr
```

**Comment by p2bauer** [comment]
@TheGameProfi ah yep, i cut out too much of my yaml, sorry!  I just modified the comment - I have an initContainer which copies the file into the in-memory volume from a configmap.....   I can give it a go mounting the file directly, i just often run into issues with it being readOnly for other similar setups.

Thanks for the help!!

**Comment by TheGameProfi** [comment]
I will take a look at v2 today, and probably release it which has big changes, including a separate config folder.
And then i will look into backporting the config folder for v1.

**Comment by TheGameProfi** [comment]
@p2bauer 
I just deployed the v1.2 version, it is now possible to locate the config at `/scraparr/config/config.cnf` if this will help you kubernetes config

**Comment by JarbasAl** [comment]
the latest version with yaml config is launching for me, but im running into #46 

just FYI this is my compose file
```
  scraparr:
    image: ghcr.io/thecfu/scraparr:latest
    container_name: scraparr
    ports:
      - ${SCRAPARR_PORT}:7100
    volumes:
      - ${CONFIG_BASE_DIR}/scraparr:/scraparr/config
    networks:
      - traefik_network
```

thanks for the quick reply!
