### ISSUE TITLE
Can't get readarr or bazarr metrics to show

### ISSUE THREAD

**Issue by itsgiff** [thecfu/scraparr#74]
I enabled the new integration according to the config file but the metrics are not showing in the scrape url. There are also no errors in the docker logs.

From inside the container I have validated that it's reading the most recent updates in the config file:

```
/ # cat scraparr/config/config.yaml 
prowlarr:
  url: http://host:9696
  api_key: <apikey>
  alias: prowlarr
  api_version: v1
#  detailed: true

sonarr:
  url: http://host:8989
  api_key: <apikey>
  alias: sonarr
  api_version: v3
#  detailed: true

radarr:
  url: http://host:7878
  api_key: <apikey>
  alias: radarr
  api_version: v3
#  detailed: true

bazarr:
  url: http://host:6767
  api_key: <apikey>
  alias: bazarr
#  detailed: true

readarr:
  url: http://host:8780
  api_key: <apikey>
  alias: readarr_audio
  api_version: v1
#  detailed: true

readarr:
  url: http://host:8781
  api_key: <apikey>
  alias: readarr_ebook
  api_version: v1
#  detailed: true

## not supported yet

# lidarr:
#   url: http://host:8686
#   api_key: <apikey>
#   alias: lidarr
#   api_version: v1
```
