### ISSUE TITLE
Scraparr only scrapes the last defined Readarr instance in the config

### ISSUE THREAD

**Issue by itsgiff** [thecfu/scraparr#89]
When defining multiple readarr instances in the config.yaml, Scraparr only scrapes the last defined instance. In the following configuration, only ebooks are scraped, and audiobooks is ignored.

**Steps to reproduce the behavior:**
1) Configure Scraparr with multiple readarr instances as follows:

```
readarr:
  url: http://example.com:8787
  api_key: <api-key>
  alias: audiobooks

readarr:
  url: http://example.com:8780
  api_key: <api-key>
  alias: ebooks
```

2) Start Scraparr

3) Observe that only ebooks data is scraped and reported.

**Expected behavior**
Scraparr should recognize and scrape both readarr instances, allowing metrics collection from both audiobooks and ebooks.

**Version**
2.20.1

**Comment by TheGameProfi** [comment]
Hey there for mutli Instances both of them need to be defined in the same Group like this:
```yaml
readarr:
  - url: http://readarr1:8989
    api_key: key
    alias: readarr1
  - api_key: key
    url: http://readarr2:8989
    alias: readarr2
```

The first Option/Setting needs to include a `-` and then the rest of the same instance is indented. A second Instance is initialized by the `-`.
